# report_config.toml

[workbook]
output = "s3://alpha-pay-modelling/Testing/OFFSEN-example_report.xlsx"

[defaults]
table_style = "Table Style Medium 1"
spacing_rows = 2
default_col_width = 14
title_font_size = 14
subtitle_font_size = 12
footnote_font_size = 9
[formats.default]
num_format = ""
width = 14
[formats.named.money]
num_format = "£#,##0"

[formats.named.date]
num_format = "dd-mmm-yy"

[formats.named.percent]
num_format = "0.0%"

[formats.named.fte]
num_format = "#,##0.0"

[formats.named.headcount]
num_format = "#,##0"

# Set column name matchers to allow matching to named format
[formats.matchers]
"(?i)date" = "date"
"(?i)headcount" = "headcount"
"(?i)cost|£" = "money"
"(?i)rate|percent|pct|%" = "percent"
"(?i)fte" = "fte"

[[sheets]]
name = "Summary"
title = "Pay model — summary by grade (function source)"
orientation = "landscape"
fit_to_pages = [1, 0]
# Header and footer only show when printing, so may be of little use
#header = "&LPay Modelling – OFFICIAL SENSITIVE&C&Ampersand Co&RPage &P of &N"
#footer = "&COFFICIAL SENSITIVE"
protective_marking = "OFFICIAL SENSITIVE"
protective_marking_span = 20
footnotes = [
  "Footnotes: ",
  "1. Costs are illustrative.",
  "2. As‑of date and scenario are examples only."
]

# 1) Single DataFrame via dotted function
[[sheets.tables]]
title = "Table 1. Base pay by grade (function)"
#start_cell = "A5"
source = [
    { type = "function", dotted = "builders.build_base_pay_by_grade", kwargs = { asof = "2025-03-31", scenario = "Central" }}
]
table_notes = [
  "Notes: ",
  "1. Table shows latest position.",
  "2. Includes all on-strength staff."
]

# 4) Simple chart
[[sheets.charts]]
title = "Chart 1. Example"
# Use an explicit cell reference for chart placement.  The code can't tell how big a chart is when on the sheet, so table positions may also need to be explitly set.
start_cell = "K5"
source = [
  { type = "function", dotted = "builders.make_chart" }
]
chart_notes_start_cell = "K25"
chart_notes = [
  "Notes: ",
  "1. Chart shows latest position.",
  "2. Includes all on-strength staff."
]

# 2) Dict-of-DataFrames via dotted function (select with 'key')
[[sheets.tables]]
title = "Table 2. On‑cost rates."
source = [
  { type = "function", dotted = "builders.build_pay_tables", kwargs = { asof = "2025-03-31", scenario = "High" }, key = "on_costs"}
]

# 3) Empty DataFrame to test '(no data)' branch
[[sheets.tables]]
title = "Table 3. Empty example (no data)"
source = [
  { type = "function", dotted = "builders.build_empty_table" }
]



